{% set version = "1.1" %}

package:
  name: mkdocs-bootswatch
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mkdocs-bootswatch/mkdocs-bootswatch-{{ version }}.tar.gz
  sha256: cc999ba15a3ce2a46eab35fcaabea9907f5c74bc49e79d9c866b51d4b0fa7f33

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.1

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - mkdocs_bootswatch
    - mkdocs_bootswatch.cerulean
    - mkdocs_bootswatch.cosmo
    - mkdocs_bootswatch.cyborg
    - mkdocs_bootswatch.darkly
    - mkdocs_bootswatch.flatly
    - mkdocs_bootswatch.journal
    - mkdocs_bootswatch.litera
    - mkdocs_bootswatch.lumen
    - mkdocs_bootswatch.lux
    - mkdocs_bootswatch.materia
    - mkdocs_bootswatch.minty
    - mkdocs_bootswatch.pulse
    - mkdocs_bootswatch.sandstone
    - mkdocs_bootswatch.simplex
    - mkdocs_bootswatch.slate
    - mkdocs_bootswatch.solar
    - mkdocs_bootswatch.spacelab
    - mkdocs_bootswatch.superhero
    - mkdocs_bootswatch.united
    - mkdocs_bootswatch.yeti

about:
  home: http://www.mkdocs.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'Bootswatch themes for MkDocs'

extra:
  recipe-maintainers:
    - ocefpaf
