travis:
  secure:
    BINSTAR_TOKEN: UbHJ4kbKsn/Ytlpzjqi9MRy59YttE5LBPHh3NIEGouLI4pl11uvgofImvW3Wg7MG/8u8VF8IALD/OGXk0plUcIJ0ugAxg+RCZGgK9t/AELpi0MY2KD+pLpohXhfHwSQBhom7QMHj2M38Gq4uSXuBUfq3BJv/OepyRf+mR4VsK7dfkn9epabB38IX6I8aRAXlkTzalsJz4AGlZWZjvaYL3rhXzfCZuUqJY9moT17TG/h4cBdWLQr6SmHL6IlIAVRAruRpEe9SZyvrVNt6f7SOZ87EYxJ0s0wGBXaQG5WT2Qq55loJaCPhdhm8IboggyKy0TpD+ghlL9ZgWnwVXzrKw2x81Q9zo3z8GVivr2vWCsT8z8VFccwxmrR6VmhNPSYLC0n8mbzYEVkQFhXdtDxdkZD4/696JtBm8MZ/RjyQDzytDsAvpAAc5RTcrSWUc2wHD91O0+Juwy/y2Zb+++Aq6Rqbt8kA8kf4AV4xs945urJzVV+F6ytzcbbwm7i4yPH7dxiqB/D39ES+GwOzYo2hONaGgiCKLhGl9/NaOpqSppVjEeuWASLir5QDlgC6c7UdpWpll/nSaHRlIVsmIFxZHePCMFsPhXJm+LnI+6/qe6yFoqTt7eMKSYz9YsWkLUt9GwqjXVGvE6mX28kIM9wmPnTXfmb5DRgcM3oG4DPqRoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
